// Similar setup as activate.js
// ... Firebase Admin SDK initialization ...

exports.handler = async function(event) {
    // ... logic to get fcmToken from Blob storage based on deviceId ...
    const message = { data: { action: 'deactivate' }, token: fcmToken };
    await admin.messaging().send(message);
    // ... return success/error response ...
};

// functions/log-crash.js
exports.handler = async function(event) {
    // ... logic to parse crash data from event.body ...
    // ... get a "crashes" store from Netlify Blobs ...
    // ... save the crash log with a timestamp and deviceId ...
    // ... return success ...
};
