[build]
  # This line is the only change needed.
  # It now correctly points to the directory where your functions are located.
  functions = "netlify/functions/"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
